
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/orderservice
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: 1234 #PasswordEncoder.encode(password)

springfox:
  documentation:
    swagger-ui:
      enabled: true

logging:
  level:
    root: info